version: "3.8"
services:
  webapp:
    build:
      context: ./src
      dockerfile: Dockerfile
    image: next-feature-demo
    environment:
      MONGO_USERNAME: root
      MONGO_PASSWORD: example
      MONGO_HOSTNAME: db
      MONGO_PORT: 27017
      MONGO_DB: test
    restart: always
    volumes:
      - ./src:/app
    ports:
      - "3000:3000"
    networks:
      - next-feature-demo

  db:
    build:
      context: ./mongo
      dockerfile: Dockerfile
    restart: always
    image: next-feature-db
    volumes:
      - data-volume:/data/db
    environment:
      MONGO_INITDB_DATABASE: test
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    networks:
      - next-feature-demo
networks:
  next-feature-demo:
    driver: bridge

volumes:
  data-volume:
