version: "3.8"
services:
  webapp:
    build:
      context: ./src
      dockerfile: Dockerfile.prod
    image: next-js-typescript
    environment:
      MONGO_USERNAME: root
      MONGO_PASSWORD: example
      MONGO_HOSTNAME: db
      MONGO_PORT: 27017
      MONGO_DB: test
      REVALIDATION_SECRET: thisisasecret
    restart: always
    depends_on:
      - db
    networks:
      - next-network
    volumes:
      - ./src:/app
    ports:
      - "80:80"

  db:
    build:
      context: ./mongo
      dockerfile: Dockerfile
    restart: always
    image: next-mongo-db
    volumes:
      - data-volume:/data/db
    environment:
      MONGO_INITDB_DATABASE: test
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    networks:
      - next-network
networks:
  next-network:
    driver: bridge

volumes:
  data-volume:
